"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, FileText, Fingerprint, Radar, Terminal, Waypoints } from "lucide-react";
import DossierNavigation from "@/app/dossier/DossierNavigation";
import OverviewSection from "@/app/dossier/OverviewSection";
import CapabilitiesSection, { normalizeCapabilities } from "@/app/dossier/CapabilitiesSection";
import RawEvidenceSection from "@/app/dossier/RawEvidenceSection";
import type { EvidenceGroupData } from "@/app/dossier/AlertsSection";
import type { Finding } from "@/lib/artifactScan/types";
import type { ReportFinding, ReportScan } from "@/lib/reportContract";
import reportStyles from "@/app/dossier/reportShell.module.css";
import immutableStyles from "@/app/dossier/immutableReport.module.css";
import ArtifactFindingsSection from "./ArtifactFindingsSection";

type Artifact = { id: string; display_name: string; source: string; source_ref: string; owner?: string | null };
type ScanRow = { id: string; artifact_id: string; decision: string; source?: string; verdict?: string; severity?: string; decision_reason?: string; public_outcome?: string | null; coverage_percent?: number; risk_score?: number; malware_score?: number; capability_assessment?: unknown; analysis_coverage?: unknown; analysis_status?: string; findings?: Finding[]; scanned_at?: string };
type Section = "overview" | "findings" | "capabilities" | "raw";
const sections = [{ id: "overview" as const, label: "Overview", icon: Radar }, { id: "findings" as const, label: "Findings", icon: AlertTriangle }, { id: "capabilities" as const, label: "Capabilities", icon: Waypoints }, { id: "raw" as const, label: "Raw evidence", icon: Terminal }];

export default function ArtifactReport({ artifact, scan, kind }: { artifact: Artifact; scan: ScanRow; kind: string }) {
  const [active, setActive] = useState<Section>("overview"); const findings = Array.isArray(scan.findings) ? scan.findings : []; const capabilities = useMemo(() => capabilitiesFrom(findings, scan.capability_assessment), [findings, scan.capability_assessment]); const reportScan = useMemo(() => toReportScan(artifact, scan, capabilities), [artifact, scan, capabilities]); const grouped = useMemo(() => groupFindings(findings), [findings]); const actionable = grouped.filter((item) => item.actionability === "block" || item.actionability === "review"); const notes = grouped.filter((item) => item.actionability !== "block" && item.actionability !== "review");
  useEffect(() => { const select = () => { const value = window.location.hash.slice(1) as Section; if (sections.some((item) => item.id === value)) setActive(value); }; select(); window.addEventListener("hashchange", select); return () => window.removeEventListener("hashchange", select); }, []);
  const count = (section: Section) => section === "findings" ? findings.length : section === "capabilities" ? Object.keys(capabilities).length : 0;
  return <main className={`dossierPage ${reportStyles.shell}`}><Link className={`dossierBack ${reportStyles.back}`} href={`/registry/${kind}`}>Back to artifact registry</Link><section className={immutableStyles.immutableBar} aria-label="Immutable report identity"><span className={immutableStyles.lock}><Fingerprint aria-hidden="true"/></span><div><span>Immutable artifact report</span><strong>Evidence is locked to this exact source and scan.</strong><details><summary>About immutable reports</summary><p>Future scans cannot replace the findings or decision shown on this URL.</p></details></div><dl><div><dt>Scan</dt><dd><code>{scan.id}</code></dd></div><div><dt>Artifact</dt><dd><code>{artifact.id.slice(0, 12)}</code></dd></div></dl></section><section className={reportStyles.mast}><header className="dossierMast"><section className="dossierIdentityPanel"><div className="dossierIdentity"><span>Artifact scan report</span><h1>{artifact.display_name}</h1><p>{artifact.source_ref}</p><code>{artifact.source} · exact resolved source</code></div></section><section className={`dossierDecision ${reportScan.decision}`}><span>Scan result</span><strong>{reportScan.decision.toUpperCase()}</strong><p>{String(reportScan.decision_reason || "Evidence is scoped to this exact artifact.")}</p><dl className="dossierHeaderFacts"><div><dt>Findings</dt><dd>{findings.length}</dd></div><div><dt>Coverage</dt><dd>{String(scan.coverage_percent ?? 0)}%</dd></div></dl></section></header></section><section className={reportStyles.pulse} aria-label="Artifact report snapshot"><article><span>Decision now</span><strong>{String(reportScan.decision_reason || "Evidence is scoped to this exact source.")}</strong><small>Exact artifact only</small></article><article><span>Findings</span><strong>{findings.length}</strong><small>source observations</small></article><article><span>Capabilities</span><strong>{Object.keys(capabilities).length}</strong><small>observed powers</small></article><article><span>Coverage</span><strong>{String(scan.coverage_percent ?? 0)}%</strong><small>source coverage</small></article><article><span>Source</span><strong>{scan.source || artifact.source}</strong><small>{artifact.source_ref}</small></article></section><div className={`dossierLayout ${reportStyles.layout}`}><DossierNavigation items={sections} active={active} count={count} onSelect={setActive}/><section className="dossierContent">{active === "overview" ? <OverviewSection decision={reportScan.decision} scan={reportScan} actionableGroups={actionable} noteGroups={notes} capabilities={capabilities} onOpenAlerts={() => { setActive("findings"); window.history.pushState(null, "", "#findings"); }}/>:null}{active === "findings" ? <ArtifactFindingsSection findings={findings}/>:null}{active === "capabilities" ? <CapabilitiesSection capabilities={capabilities}/>:null}{active === "raw" ? <RawEvidenceSection scan={reportScan} findings={findings as unknown as ReportFinding[]}/>:null}</section></div></main>;
}

function toReportScan(artifact: Artifact, scan: ScanRow, capabilities: Record<string, Record<string, unknown>>): ReportScan { const decision = ["allow", "review", "block", "incomplete"].includes(scan.decision) ? scan.decision as ReportScan["decision"] : "incomplete"; return { ...scan, id: scan.id, extension_id: artifact.id, version: "resolved", artifact_sha256: artifact.id, analysis_status: scan.analysis_status === "complete" ? "complete" : "incomplete", decision, capabilities, coverage_percent: Number(scan.coverage_percent || 0), risk_score: Number(scan.risk_score || 0), malware_score: Number(scan.malware_score || 0) } as ReportScan; }
function capabilitiesFrom(findings: Finding[], assessment: unknown) { const result = normalizeCapabilities(assessment); for (const item of findings) { const key = item.category; result[key] ||= { evidence: [] }; const evidence = result[key].evidence as unknown[]; if (!evidence.includes(item.file)) evidence.push(item.file); } return result; }
function groupFindings(findings: Finding[]): EvidenceGroupData[] { const groups = new Map<string, EvidenceGroupData>(); for (const item of findings) { const key = item.category; const actionability = item.severity === "critical" ? "block" : item.severity === "high" ? "review" : item.severity === "low" ? "low" : "contextual"; const current = groups.get(key); if (current) { current.count += 1; current.locations.push(`${item.file}${item.line ? `:${item.line}` : ""}`); } else groups.set(key, { rule: key, summary: item.title, severity: item.severity.toUpperCase(), count: 1, locations: [`${item.file}${item.line ? `:${item.line}` : ""}`], actionability, evidenceClasses: [item.category] }); } return [...groups.values()]; }
