"use client";
import Link from "next/link";
import { LoaderCircle, Search, ScanSearch } from "lucide-react";
import { useEffect, useState } from "react";
import type { ArtifactKind } from "@/lib/artifactScan/types";
import styles from "./registry.module.css";

type State = "idle" | "loading" | "queued" | "running" | "complete" | "failed";
type Body = { id?: string; status?: string; error?: string; job?: { status?: string; error?: string }; scan?: { id?: string } | null };
export default function ArtifactScanForm({ kind, placeholder }: { kind: ArtifactKind; placeholder: string }) {
  const [value, setValue] = useState(""); const [state, setState] = useState<State>("idle"); const [jobId, setJobId] = useState(""); const [scanId, setScanId] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!jobId) return; let cancelled = false; let timeout: number | undefined; let delay = 2500;
    const poll = async () => { try { const response = await fetch(`/api/scans/artifacts/${encodeURIComponent(jobId)}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})) as Body; if (cancelled) return; if (response.status === 401) { setState("failed"); setMessage("Your session expired. Sign in again to follow this scan."); return; } if (!response.ok) { setState("failed"); setMessage(body.error || "Scan progress is unavailable."); return; } const job = body.job || {}; if (job.status === "complete") { setState("complete"); setScanId(String(body.scan?.id || "")); setMessage("Scan complete. Your artifact report is ready."); return; } if (job.status === "failed") { setState("failed"); setMessage(job.error || "Artifact scan failed. Retry when the scanner is available."); return; } setState(job.status === "running" ? "running" : "queued"); setMessage(job.status === "running" ? "Analyzers are inspecting the exact artifact." : "Starting the isolated analysis runner…"); delay = Math.min(10000, delay + 1000); timeout = window.setTimeout(poll, delay); } catch { if (!cancelled) { delay = Math.min(10000, delay + 1000); timeout = window.setTimeout(poll, delay); } } };
    void poll(); return () => { cancelled = true; if (timeout) window.clearTimeout(timeout); };
  }, [jobId]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!value.trim() || ["loading", "queued", "running"].includes(state)) return; setState("loading"); setMessage(""); setScanId(""); try { const response = await fetch("/api/scans/artifacts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source: value.trim(), kind }) }); const body = await response.json().catch(() => ({})) as Body; if (response.status === 401) { setState("failed"); setMessage("Sign in to scan this artifact."); return; } if (!response.ok || !body.id) { setState("failed"); setMessage(body.error || "The artifact scan could not be queued."); return; } setJobId(String(body.id)); setState(body.status === "running" ? "running" : "queued"); setMessage("Scan queued. Preparing the exact source for analysis."); } catch { setState("failed"); setMessage("The scan service could not be reached. Check your connection and try again."); } }
  const busy = ["loading", "queued", "running"].includes(state);
  return <><form className={styles.artifactSearch} onSubmit={submit}><Search aria-hidden="true"/><input value={value} onChange={(event) => setValue(event.target.value)} name="source" placeholder={placeholder} aria-label={`Search ${kind}`} /><button type="submit" disabled={busy || !value.trim()}>{state === "loading" ? <><LoaderCircle className="spin" size={15}/> Queueing</> : state === "queued" ? "Queued" : state === "running" ? <><LoaderCircle className="spin" size={15}/> Analyzing</> : <>Scan {kind}</>}</button></form>{message ? <span className={state === "failed" ? "actionError" : "actionNotice"} role="status">{message}</span> : null}{state === "failed" ? <button className="artifactRetry" type="button" onClick={() => { setState("idle"); setJobId(""); }}>Retry</button> : null}{state === "failed" && message.includes("Sign in") ? <Link className="artifactSignIn" href="/account">Sign in to scan</Link> : null}{state === "complete" && scanId ? <Link className="artifactReportLink" href={`/registry/${registryPath(kind)}/report/${encodeURIComponent(scanId)}`}>Open artifact report <ScanSearch size={14}/></Link> : null}</>;
}
function registryPath(kind: ArtifactKind) { return kind === "mcp" ? "mcp-servers" : `${kind}s`; }
