import { runAllChecks } from "./checks"; import { scoreFindings } from "./score"; import { fetchGithubSource } from "./fetchers/github"; import { fetchNpmSource } from "./fetchers/npm"; import type { ArtifactKind, ArtifactScanResult, ArtifactSourceType, SourceFile } from "./types";
export type ArtifactLocator =
  | { source: "github"; owner: string; repo: string; path?: string }
  | { source: "npm"; packageName: string; version: string };
export async function scanArtifactSource(locator: ArtifactLocator, kind: ArtifactKind) {
  const fetched = locator.source === "github" ? await fetchGithubSource(locator.owner, locator.repo, locator.path) : await fetchNpmSource(locator.packageName, locator.version);
  return analyzeArtifact(fetched.files, { kind, source: locator.source, partial: fetched.partial, warnings: fetched.warnings });
}
export function analyzeArtifact(files: SourceFile[], options: { kind?: ArtifactKind; source?: ArtifactSourceType; partial?: boolean; warnings?: string[] } = {}): ArtifactScanResult & ReturnType<typeof scoreFindings> & { analysis_status: "complete" } { const checked = runAllChecks(files, options); const scan = { findings: checked.findings, scannedFiles: files.length, linesAnalyzed: files.reduce((n, f) => n + f.content.split(/\r?\n/).length, 0), checksRun: checked.checksRun, partial: options.partial === true, scanWarnings: options.warnings || [] }; const score = scoreFindings(scan.findings); return { ...scan, ...score, analysis_status: "complete", analysis_coverage: { status: "complete" as const, ...(scan.partial ? { partial: true } : {}) } }; }
export async function persistArtifactResult(db: { from: (table: string) => any }, artifactId: string, result: ArtifactScanResult & ReturnType<typeof scoreFindings>) { const coverage_percent = result.scannedFiles > 0 ? result.partial ? 60 : 100 : 0; const row = { artifact_id: artifactId, decision: result.decision, verdict: result.verdict, severity: result.severity, decision_reason: result.decision_reason, public_outcome: result.decision === "block" ? "preventive_block" : result.decision === "review" ? "investigate" : null, coverage_percent, risk_score: result.risk_score, malware_score: result.malware_score, capability_assessment: result.capability_assessment, analysis_coverage: result.analysis_coverage, analysis_status: "complete", findings: result.findings, scanned_at: new Date().toISOString() }; const written = await db.from("artifact_scans").insert(row).select("*").single(); if (written.error) throw written.error; return { result, row: written.data }; }
export async function persistArtifactScan(db: { from: (table: string) => any }, artifactId: string, files: SourceFile[], options: { kind?: ArtifactKind; source?: ArtifactSourceType; partial?: boolean; warnings?: string[] } = {}) { return persistArtifactResult(db, artifactId, analyzeArtifact(files, options)); }
